
name: Deploy Application

on:
    push:
      branches:
        - instalacion-laravel


jobs:
    create-deployment-artifacts:
        
        name: Create Deployment Artifacts
        runs-on: ubuntu-latest
        steps:
                - name: Checkout
                  uses: actions/checkout@v2
                    with:
                        fetch-depth: 0

                - name: Set up Node.js
                    uses: actions/setup-node@v1
                    with:
                        node-version: '18.x'


                - name: Compile CSS and Javascript
                  run: |
                    npm install
                    npm run dev