name: Aplicacion Desplegada

# Despliegue de la aplicacion
on:
  push:
    branches:
      - instalacion-laravel

jobs:
  create-deployments-artifacts:
    name: Crear artefactos de despliegue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none
 
      - name: Run composer install
        run: composer install -n --prefer-dist
 
      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

